// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Tpk6Lnn59R615-qGpgkUnTx4wyUKL4w',
    appId: '1:486496463953:web:fa2adbd770814578071c70',
    messagingSenderId: '486496463953',
    projectId: 'powerup-e769f',
    authDomain: 'powerup-e769f.firebaseapp.com',
    storageBucket: 'powerup-e769f.appspot.com',
    measurementId: 'G-18D8E1XNPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfTTrnBRr06yRbrSau7qJyF1TJAw_O2jg',
    appId: '1:486496463953:android:0ccfcf6314f00bf9071c70',
    messagingSenderId: '486496463953',
    projectId: 'powerup-e769f',
    storageBucket: 'powerup-e769f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmYOqmUTyuzb-ujPO7db-_Pd_Cf6gDOJU',
    appId: '1:486496463953:ios:ca4e78a8bffc1885071c70',
    messagingSenderId: '486496463953',
    projectId: 'powerup-e769f',
    storageBucket: 'powerup-e769f.appspot.com',
    iosClientId: '486496463953-dfk835009src6u2tl8tlu32n3jv9lkuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.jueguito2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmYOqmUTyuzb-ujPO7db-_Pd_Cf6gDOJU',
    appId: '1:486496463953:ios:a9f0173a01e15d6f071c70',
    messagingSenderId: '486496463953',
    projectId: 'powerup-e769f',
    storageBucket: 'powerup-e769f.appspot.com',
    iosClientId: '486496463953-fdeob539a68mqn9amruvp5t2uoj21r6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.jueguito2.RunnerTests',
  );
}
